### ISSUE TITLE
导出的模型输出为固定值？

### ISSUE THREAD

**Issue by Anivie** [Aimol-l/SAM2Export#5]
作者您好，image_decoder的pred_mask为最终输出的掩码图像，在最终输出的掩码图像，在`Output { name: "pred_mask", output_type: Tensor { ty: Float32, dimensions: [-1, -1, -1, -1] } }`中可以看到四个通道都是动态值

在官方的`sam2.sam2_image_predictor.SAM2ImagePredictor.predict`中提到返回值是：
> The output masks in CxHxW format, where C is the  number of masks, and (H, W) is the original image size.

也就是说官方的版本是支持多输出的，但是作者提供的onnx版本测试发现无论输入几个点输出都是(1, 1, H, W)，请问这是进行了自动的选择还是推理时就只包含一个mask？

如果我们希望使用这个模型来进行everything模式的推理应该怎么办呢

**Comment by Aimol-l** [comment]
你是否完全清楚everything模式的推理逻辑？
就我所知道的，官方是在一张图片上先均匀生成许多点作为prompt。然后进行一次encoder,后续进行了并行decoder,因此pred_mask会是 [batch,1,1024,1024]。
你需要修改decoder 的输入维度，修改为支持动态batch,本项目可以认为是固定batch = 1，推理的时候是只包含一个mask。
有n组prompt进行并行decoder,那么输出pred_mask就应该要是 [n,1,1024,1024]




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aimol-l/SAM2Export"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 晚上9:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Aimol-l/SAM2Export] 导出的模型输出为固定值？ (Issue #5)





 
作者您好，image_decoder的pred_mask为最终输出的掩码图像，在最终输出的掩码图像，在Output { name: "pred_mask", output_type: Tensor { ty: Float32, dimensions: [-1, -1, -1, -1] } }中可以看到四个通道都是动态值
 
在官方的sam2.sam2_image_predictor.SAM2ImagePredictor.predict中提到返回值是：
  
The output masks in CxHxW format, where C is the  number of masks, and (H, W) is the original image size.
  
也就是说官方的版本是支持多输出的，但是作者提供的onnx版本测试发现无论输出几个点输出都是(1, 1, H, W)，请问这是进行了自动的选择还是推理时就只包含一个mask？
 
如果我们希望使用这个模型来进行everything模式的推理应该怎么办呢

**Comment by Anivie** [comment]
感谢回答
